curl https://blocklistproject.github.io/Lists/scam.txt > yabah
printf "\n" >> yabah
curl https://blocklistproject.github.io/Lists/abuse.txt >> yabah
printf "\n" >> yabah
curl https://blocklistproject.github.io/Lists/malware.txt >> yabah
printf "\n" >> yabah
curl https://blocklistproject.github.io/Lists/ads.txt >> yabah
printf "\n" >> yabah
curl https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts >> yabah
printf "\n" >> yabah
curl https://ewpratten.retrylife.ca/youtube_ad_blocklist/hosts.ipv4.txt >> yabah
